### ISSUE TITLE
[Linux] [Prism Launcher] [1.19.2] Incompatible with Cloth Config

### ISSUE THREAD

**Issue by DarkblooM-IO** [homchom/recode#38]
Hi

Game crashes on startup due to Cloth Config incompatibility.
[Full log](https://pastebin.com/rjinLW3H) (password: GaTx3D62Gj)

Do I switch Cloth Config version? Or Recode?

**Comment by tk2217** [comment]
Proper paste (I should really find a nice way to deobf these): https://paste.gg/p/anonymous/c0e58586b95046a89c2d5702909368cf

**Comment by tk2217** [comment]
You don't even have recode installed here.

**Comment by tk2217** [comment]
If it's popping up an error window, could you send a screenshot of that?

**Comment by DarkblooM-IO** [comment]
![screenshot](https://i.postimg.cc/RZ1wXvQ0/Screenshot-from-2023-01-13-14-30-48.png)

**Comment by DarkblooM-IO** [comment]
Any news?

**Comment by Racooder** [comment]
Same here! Windows, Prism Launcher, 1.19.2
No Mods except recode, quilted fabric API and cloth config.

Crash Report: https://paste.gg/p/anonymous/09f998fe554d4b0a83652114d42f934c
Log: https://paste.gg/p/anonymous/fc135dea33c54a42b9c574761e7c51ef

**Comment by DarkblooM-IO** [comment]
Update: I got it to run once with latest versions of Recode and Cloth Config, but it came back to instant crash the second time

![image](https://user-images.githubusercontent.com/54911078/230181301-9ef68598-557b-4d9e-9016-22c55f868e1e.png)

**Comment by homchom** [comment]
"fixed" in the upcoming beta 6.
