### ISSUE TITLE
Essential settings issue.

### ISSUE THREAD

**Issue by Severnarch** [homchom/recode#40]
![image](https://user-images.githubusercontent.com/86313252/213004372-5e4af3f9-e690-45b9-ab90-7e30f8f7904d.png)
Minecraft Quilt 1.19.2 (Using Quilt instead of Fabric due to errors with connecting to DF through Fabric.)

**Comment by Severnarch** [comment]
bit of an overlap tbh not too much to worry about

**Comment by Severnarch** [comment]
Mod list through MultiMC.
 - Xaero's disabled
 - Only essentials & recode have a small issue (main image above)
![image](https://user-images.githubusercontent.com/86313252/213004778-44e20a7b-61ea-4e5c-bb11-d6b1d1d614fd.png)

**Comment by homchom** [comment]
Sorry for the overdue response. This was already posted as issue #8, so I'm going to close this. With that said, a fix should happen soon, so thanks for your patience.
