### ISSUE TITLE
implement send-to-plot with "pls join" protocol

### ISSUE THREAD

**Issue by o7Moon** [homchom/recode#42]
[pls join](https://gist.github.com/o7Moon/4d8806cb739d1606715855e5e1caa4c6) is a simple protocol for client side send-to-plot. There is currently a client implementation that uses dfscript, and it works, however the protocol would benefit from having a more widely used implementation, and I think including it in recode would be the perfect way to acheive that.

It would be very intrusive if automatic joining was enabled by default, so I think there should be (at minimum) these three modes:
- off (does nothing)
- prompt (displays a clickable chat message which runs the /join command when clicked. this could be a good default)
- automatic (runs the join command immediately)

Additionally there should be a configurable cooldown to prevent abuse.

I plan on implementing this myself, is this something that would get merged?

**Comment by MrSam7K** [comment]
I don't think it's a good idea, also imo you should've posted this to discord for more feedback.

**Comment by homchom** [comment]
In general I'm very opposed to features like this because I don't want playing a plot to "require" recode (or any mod) for an optimal playing experience. We're probably going to come up with a more polished and hidden protocol later, but in any case it will have a prompt, which we do not yet have the infrastructure to code easily.

**Comment by o7Moon** [comment]
> I don't want playing a plot to "require" recode (or any mod) for an optimal playing experience. We're probably going to come up with a more polished and hidden protocol later

I've tried to design the protocol specifically to address this issue, the message tells the player what to do in the case that they don't have any kind of mod. 

Manually typing the command will never be as efficient as having a mod do it automatically, but I don't think that it makes sense to deny a convenience feature because of the vanilla client not having the same convenience.
