### ISSUE TITLE
welp there goes recode

### ISSUE THREAD

**Issue by giftedl** [homchom/recode#46]
![javaw_SuknO9ScNu](https://user-images.githubusercontent.com/52332868/234281566-8dc3fcb2-138f-4b4b-ab71-3c3777a9d072.png)
there goes recode

Jokes aside, we need recode to update to 1.19.4.

**Comment by akarahdev** [comment]
for now, just use development builds
https://github.com/homchom/recode/actions/runs/4711114432#artifacts
stability is not confirmed but it worked well for me on windows 10

**Comment by homchom** [comment]
upcoming version is already on 1.19.4 which I will release asap. this is technically already done on main though so closing this
