### ISSUE TITLE
Kicked for spam when unclaiming a plot.

### ISSUE THREAD

**Issue by Electric131** [homchom/recode#56]
Pretty simple and easy to reproduce, simply claim a plot and then unclaim it. When you are sent to spawn, recode spams automation commands. (Requires them to be on afaik)

**Comment by MrSam7K** [comment]
Be sure to unclaim your most popular plot (joke)

**Comment by homchom** [comment]
@Electric131 this doesn't happen for me. does it happen for you every time, and if not, is there a pattern to it?

**Comment by homchom** [comment]
@Electric131 @MrSam7K Do you use CodeClient?

**Comment by Electric131** [comment]
I do use CodeClient, yes. So ig it could be a CodeClient bug instead.

**Comment by homchom** [comment]
@Electric131 Please check if it happens without recode.

**Comment by MrSam7K** [comment]
Yes, CodeClient WITH recode kicks you. CodeClient alone bugs you out but does not kick you

**Comment by GeorgeRNG** [comment]
This was fully a side effect of a codeclient issue, so download the [latest version](https://github.com/DFOnline/CodeClient/releases/tag/v108).
If you get issues like getting teleported like that, try running /[fixcc](https://github.com/DFOnline/CodeClient/wiki/commands#fixcc) (while bugging out), disabling noclip, or uninstalling codeclient. If those fix it pester me :star_struck:

**Comment by homchom** [comment]
fixed via https://github.com/DFOnline/CodeClient/commit/abe79eafb52e66753bb5864db12d4b3ebf46a0e8
