### ISSUE TITLE
The flight speed: normal -> fast toggle doesn't toggle

### ISSUE THREAD

**Issue by Faroras** [homchom/recode#6]
when using the keybind for the fast flight speed toggle the flight speed just stays on the percent of the fast speed but
doesn't go back anymore to the default 100% flight speed

**Comment by homchom** [comment]
fixed in 0.1.0-beta.3. while i was at it i also made it so the toggle state is detected using the player's attributes, rather than a convoluted detection system, so it might be more consistent in some edge cases too.
