### ISSUE TITLE
Crash on clicking the recourcepacks button

### ISSUE THREAD

**Issue by JayRPlayz** [homchom/recode#69]
every time i click the recourcepack button, its crashes my game, if i dont use recode (newest version on modrinth), it doesnt crash.

Crash report:
[crash-2023-12-29_10.38.14-client.txt](https://github.com/homchom/recode/files/13792428/crash-2023-12-29_10.38.14-client.txt)

**Comment by Drahna** [comment]
I am also having this issue
Crash reason:
Caused by: java.lang.NullPointerException: Cannot invoke "net.kyori.adventure.pointer.Pointered.getOrDefault(net.kyori.adventure.pointer.Pointer, Object)" because "ptr" is null

EDIT: I am using the 0.1.0 beta 9 for 1.20.2

**Comment by homchom** [comment]
Forgot to comment on this, but it is fixed in the next update.
