### ISSUE TITLE
Game crashing through PolyMC on Linux

### ISSUE THREAD

**Issue by balt-dev** [homchom/recode#7]
Here's my crash log
[crash-2022-08-15_22.12.15-client.txt](https://github.com/homchom/recode/files/9347669/crash-2022-08-15_22.12.15-client.txt)

**Comment by homchom** [comment]
Known issue. Copied from the Discord server:

> If recode crashes on startup for you with a `org.newsclub.net.unix.AFUNIXSocketException`, it is probably related to the current Discord RPC feature (which we intend to replace with a more stable replacement). There are two workarounds for this:
>
> 1. Use a different, supported JVM, one that doesn't crash. For example, Temurin JDKs do not work.
> 2. Manually disable Discord RPC in the mod's config file at `.minecraft/config/recode.json`. It is a JSON, so it should look something like this:```json
{
  "discordRPC": false
}
```

**Comment by homchom** [comment]
Thinking about it more, this issue has come up so often recently that in the mean time I'm going to just disable the feature by default until I fix this.

**Comment by homchom** [comment]
I implemented a try/catch as a stopgap workaround in beta 4. Also, I know this is old bu to anyone new reading this, don't use PolyMC. Its certificate has been revoked by Microsoft and is no longer a trusted FOSS project.
