### ISSUE TITLE
Fix button positioning when loaded with the Essential mod

### ISSUE THREAD

**Issue by balt-dev** [homchom/recode#8]
![image](https://user-images.githubusercontent.com/59123926/184792447-366bd1dd-e5b9-4237-97d5-d831a7eebe14.png)

**Comment by UserUNP** [comment]
fardcoding

**Comment by homchom** [comment]
A long overdue update: in the upcoming beta 6, the recode button is injected into the grid object that Minecraft uses to populate the options menu, so this might have fixed itself. But I'll test it soon and try to get a fix in beta 6 or 7 at the latest.

**Comment by homchom** [comment]
can confirm this is no longer an issue

**Comment by UserUNP** [comment]
i don't remember commenting on this

**Comment by homchom** [comment]
@UserUNP I deleted your original comment lol
